import { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { Download, FileJson, Globe, Table, X } from 'lucide-react';
import { saveAs } from 'file-saver';
const DataDownloadCenter = ({ onClose }) => {
  const { theme, selectedCountry } = useApp();
  const [downloading, setDownloading] = useState(false);
  const bg = theme === 'dark' ? 'rgba(15,23,42,0.98)' : 'rgba(255,255,255,0.98)';
  const color = theme === 'dark' ? '#fff' : '#000';
  const borderColor = theme === 'dark' ? 'rgba(59,130,246,0.3)' : 'rgba(59,130,246,0.5)';
  // Proper KML generator supporting Polygon & MultiPolygon
  const generateKML = (countryData) => {
    const geom = countryData.geometry;
    let coordinatesKML = '';
    if (geom.type === 'Polygon') {
      // Polygon: array of rings
      geom.coordinates.forEach(ring => {
        coordinatesKML += '<coordinates>';
        ring.forEach(coord => {
          coordinatesKML += `${coord[0]},${coord[1]},0 `;
        });
        coordinatesKML += '</coordinates>';
      });
    } else if (geom.type === 'MultiPolygon') {
      // MultiPolygon: array of polygons
      geom.coordinates.forEach(polygon => {
        polygon.forEach(ring => {
          coordinatesKML += '<coordinates>';
          ring.forEach(coord => {
            coordinatesKML += `${coord[0]},${coord[1]},0 `;
          });
          coordinatesKML += '</coordinates>';
        });
      });
    }
    return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${countryData.properties.name}</name>
    <description>Generated by ADHAM GIS AI - ${new Date().toISOString()}</description>
    <Style id="countryStyle">
      <LineStyle><color>ff0000ff</color><width>2</width></LineStyle>
      <PolyStyle><color>7f0080ff</color></PolyStyle>
    </Style>
    <Placemark>
      <name>${countryData.properties.name}</name>
      <description><![CDATA[
        <b>Capital:</b> ${countryData.properties.capital}<br/>
        <b>Population:</b> ${countryData.properties.pop_est.toLocaleString()}<br/>
        <b>GDP:</b> $${countryData.properties.gdp_md_est.toLocaleString()}M<br/>
        <b>Area:</b> ${countryData.properties.area_km2.toLocaleString()} km²<br/>
        <b>Density:</b> ${Math.round(countryData.properties.pop_est / countryData.properties.area_km2)}/km²<br/>
        <b>DSI:</b> ${countryData.properties._dsi?.toFixed(2) || 'N/A'}
      ]]></description>
      <styleUrl>#countryStyle</styleUrl>
      <MultiGeometry>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              ${coordinatesKML}
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </MultiGeometry>
    </Placemark>
  </Document>
</kml>`;
  };
  const downloadData = async (format) => {
    if (!selectedCountry) return;
    setDownloading(true);
    try {
      const response = await fetch('/latamCountries.json');
      const data = await response.json();
      const countryData = data.features.find(f => f.properties.name === selectedCountry.name);
      let content, mimeType, filename;
      const safeName = selectedCountry.name.toLowerCase().replace(/\s+/g, '-');
      switch(format) {
        case 'geojson':
          content = JSON.stringify(countryData, null, 2);
          mimeType = 'application/geo+json';
          filename = `${safeName}.geojson`;
          break;
        case 'kml':
          content = generateKML(countryData);
          mimeType = 'application/vnd.google-earth.kml+xml';
          filename = `${safeName}.kml`;
          break;
        case 'csv':
          const csv = `Property,Value,Unit,Source\nName,${selectedCountry.name},,Natural Earth\nCapital,${selectedCountry.capital},,World Bank\nPopulation,${selectedCountry.population},people,World Bank 2023\nGDP,${selectedCountry.gdp},million USD,World Bank 2023\nArea,${selectedCountry.area},km²,World Bank\nDensity,${selectedCountry.popDensity},per km²,Calculated\nGDP per Capita,${selectedCountry.gdpPerCapita},USD,Calculated\nDSI Score,${selectedCountry.dsi},/100,ADHAM GIS AI Engine\nData Date,2023,,World Bank\nCRS,EPSG:4326,,WGS84`;
          content = csv;
          mimeType = 'text/csv';
          filename = `${safeName}.csv`;
          break;
        default:
          content = JSON.stringify(countryData, null, 2);
          mimeType = 'application/geo+json';
          filename = `${safeName}.json`;
      }
      const blob = new Blob([content], { type: mimeType });
      saveAs(blob, filename);
    } catch (error) {
      console.error('Download error:', error);
      alert('Download failed: ' + error.message);
    }
    setDownloading(false);
  };
  const formats = [
    { id: 'geojson', name: 'GeoJSON', icon: FileJson, desc: 'Standard GIS format (QGIS/ArcGIS)', color: '#3b82f6' },
    { id: 'kml', name: 'KML', icon: Globe, desc: 'Google Earth / QGIS compatible', color: '#10b981' },
    { id: 'csv', name: 'CSV', icon: Table, desc: 'Tabular with data provenance', color: '#f59e0b' }
  ];
  return (
    <div style={{
      position: 'fixed', top: '80px', right: '20px',
      width: '340px',
      background: bg, backdropFilter: 'blur(12px)',
      borderRadius: '12px', border: '1px solid ' + borderColor,
      padding: '0', zIndex: 100, color: color,
      boxShadow: '0 10px 40px rgba(0,0,0,0.4)',
      overflow: 'hidden'
    }}>
      <div style={{ 
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        padding: '14px 16px',
        borderBottom: '1px solid ' + borderColor,
        background: 'rgba(59,130,246,0.1)'
      }}>
        <h3 style={{ margin: 0, fontSize: '14px', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Download size={16} /> Download Data
        </h3>
        <button onClick={onClose} style={{
          background: 'rgba(239,68,68,0.2)', border: 'none', borderRadius: '50%',
          width: '28px', height: '28px', cursor: 'pointer',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          color: '#ef4444'
        }}>
          <X size={16} />
        </button>
      </div>
      <div style={{ padding: '16px' }}>
        {selectedCountry ? (
          <>
            <div style={{ marginBottom: '16px', padding: '12px', background: 'rgba(59,130,246,0.1)', borderRadius: '8px' }}>
              <div style={{ fontSize: '16px', fontWeight: 700 }}>{selectedCountry.name}</div>
              <div style={{ fontSize: '11px', opacity: 0.7, marginTop: '4px' }}>DSI: {selectedCountry.dsi?.toFixed(1) || 'N/A'} | Density: {selectedCountry.popDensity}/km²</div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {formats.map(fmt => {
                const Icon = fmt.icon;
                return (
                  <button
                    key={fmt.id}
                    onClick={() => downloadData(fmt.id)}
                    disabled={downloading}
                    style={{
                      padding: '14px',
                      background: 'rgba(255,255,255,0.05)',
                      border: '1px solid ' + borderColor,
                      borderRadius: '8px',
                      cursor: 'pointer',
                      display: 'flex', alignItems: 'center', gap: '12px',
                      opacity: downloading ? 0.6 : 1
                    }}
                    onMouseEnter={(e) => !downloading && (e.currentTarget.style.background = 'rgba(59,130,246,0.1)')}
                    onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.05)'}
                  >
                    <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: fmt.color + '20', display: 'flex', alignItems: 'center', justifyContent: 'center', color: fmt.color }}>
                      <Icon size={20} />
                    </div>
                    <div style={{ textAlign: 'left', flex: 1 }}>
                      <div style={{ fontSize: '13px', fontWeight: 600 }}>{fmt.name}</div>
                      <div style={{ fontSize: '11px', opacity: 0.7 }}>{fmt.desc}</div>
                    </div>
                  </button>
                );
              })}
            </div>
          </>
        ) : (
          <div style={{ textAlign: 'center', padding: '40px 0', opacity: 0.7 }}>
            <div>Select a country to download data</div>
          </div>
        )}
      </div>
    </div>
  );
};
export default DataDownloadCenter;
